# Generated by Django 5.2.12 on 2026-04-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='subtitle_ta',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
